language: cpp
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq make automake g++ libboost-dev libboost-regex-dev libgmp-dev python-plastex
install: cd problemtools && make
script: cd problems && make all
